export const VIDEO_LIST_REQUEST = "VIDEO_LIST_REQUEST"
export const VIDEO_LIST_SUCCESS = "VIDEO_LIST_SUCCESS"
export const VIDEO_LIST_FAIL = "VIDEO_LIST_FAIL"

export const VIDEO_DETAILS_REQUEST = "VIDEO_DETAILS_REQUEST"
export const VIDEO_DETAILS_SUCCESS = "VIDEO_DETAILS_SUCCESS"
export const VIDEO_DETAILS_FAIL = "VIDEO_DETAILS_FAIL"

export const VIDEO_SEARCH_REQUEST = "VIDEO_SEARCH_REQUEST"
export const VIDEO_SEARCH_SUCCESS = "VIDEO_SEARCH_SUCCESS"
export const VIDEO_SEARCH_FAIL = "VIDEO_SEARCH_FAIL"

export const VIDEO_UPLOAD_REQUEST = "VIDEO_UPLOAD_REQUEST"
export const VIDEO_UPLOAD_SUCCESS = "VIDEO_UPLOAD_SUCCESS"
export const VIDEO_UPLOAD_FAIL = "VIDEO_UPLOAD_FAIL"

export const COMMENT_POST_REQUEST = "COMMENT_POST_REQUEST"
export const COMMENT_POST_SUCCESS = "COMMENT_POST_SUCCESS"
export const COMMENT_POST_FAIL = "COMMENT_POST_FAIL"

export const COMMENT_LIST_REQUEST = "COMMENT_LIST_REQUEST"
export const COMMENT_LIST_SUCCESS = "COMMENT_LIST_SUCCESS"
export const COMMENT_LIST_FAIL = "COMMENT_LIST_FAIL"