# Generated by Django 4.2.6 on 2023-11-01 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('about', models.TextField(blank=True, null=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('follower_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('profile_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.user_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_text', models.TextField(blank=True, null=True)),
                ('comment_likes', models.IntegerField(blank=True, default=0, null=True)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('video_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.video')),
            ],
        ),
    ]
