# Generated by Django 4.2.6 on 2023-11-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_profile_profile_photo_video_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='video_id',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='user_id',
            new_name='user',
        ),
    ]
