# Generated by Django 4.2.6 on 2023-11-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_video_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='thumbnail',
            new_name='thumbnail_file',
        ),
    ]
