# Generated by Django 4.2.6 on 2023-11-28 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_thumbnail_video_thumbnail_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='joined_date',
        ),
    ]
