# Generated by Django 4.2.6 on 2023-11-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_user_profile_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos'),
        ),
    ]
