# Generated by Django 4.2.6 on 2023-11-30 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_alter_user_profile_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('like', models.BooleanField(default=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.video')),
            ],
        ),
    ]
