# Generated by Django 4.2.6 on 2023-12-02 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='follower_id',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='follower',
            name='followed_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
