videos = [
    {
        "_id": "1",
        "title": "A Tattoo Artist Showing a Customer A Tattoo Design Using An Ipad",
        "file_name": "video1.mp4",
        "views_count": "234532",
        "video_channel_name": "StellarExplorers",
        "video_channel_profile_photo": "user1.jpg",
    },
    {
        "_id": "2",
        "title": "Catching And Releasing A Big Carp Fish In The Lake",
        "file_name": "video2.mp4",
        "views_count": "4352",
        "video_channel_name": "CreativeMinds",
        "video_channel_profile_photo": "user2.jpg",
    },
    {
        "_id": "3",
        "title": "Football Training",
        "file_name": "video3.mp4",
        "views_count": "5332444",
        "video_channel_name": "DIYEnthusiasts",
        "video_channel_profile_photo": "user3.jpg",
    },
    {
        "_id": "4",
        "title": "A Man Doing Pull Ups Exercise On A Steel Bar",
        "file_name": "video4.mp4",
        "views_count": "133443",
        "video_channel_name": "FitnessFanatics",
        "video_channel_profile_photo": "user4.jpg",
    },
    {
        "_id": "5",
        "title": "Drone Footage of a Coastline",
        "file_name": "video5.mp4",
        "views_count": "434224455",
        "video_channel_name": "TravelBuddies",
        "video_channel_profile_photo": "user5.jpg",
    },
    {
        "_id": "6",
        "title": "A Man Working Out in the Gym",
        "file_name": "video6.mp4",
        "views_count": "232345",
        "video_channel_name": "ISFitness",
        "video_channel_profile_photo": "user6.jpg",
    },
    {
        "_id": "7",
        "title": "A Person Working On A High Communication Tower",
        "file_name": "video7.mp4",
        "views_count": "32245",
        "video_channel_name": "NatureLovers",
        "video_channel_profile_photo": "user7.jpg",
    },
    {
        "_id": "8",
        "title": "Tourist Doing a Jump Shot at the Beach Signage",
        "file_name": "video8.mp4",
        "views_count": "13",
        "video_channel_name": "MovieBuffZone",
        "video_channel_profile_photo": "user8.jpg",
    }
]